import { Geist, Geist_Mono } from "next/font/google";
//sub se pehly layout.js file run hoti hai, usme hum common components ko import karenge, jaise header, footer, etc. aur page.js me hum section specific components ko import karenge, jaise banner section, latest courses section, etc.
import "./globals.css";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
